### ISSUE TITLE
No boot entry is made if installing using "Manual Partitioning" option

### ISSUE THREAD

**Issue by artazol** [Nobara-Project/rpm-sources#51] opened 2024-06-08 05:20 UTC
Device: ThinkPad P14s Gen 2 (AMD)
ISO: Nobara-39-KDE-2024-01-24.iso (from official website)

After the installation process via Calamares completes, the EFI boot entry for Nobara is absent from the boot device selection. After adding the boot entry via efibootmgr manually, the installed OS boots fine.

Just to make sure - I followed the manual partitioning instructions on feed.nobaraproject.org exactly, so required mount points were present.

**Comment by matte-schwartz** [comment] 2024-06-11 19:08
I tried to repro this on the steam deck image but I wasn't able to. I'll try the KDE one in a VM just to confirm.

**Comment by GloriousEggroll** [comment] 2024-07-24 17:57
closing -- still unable to reproduce

**Closed by GloriousEggroll** 2024-07-24 17:57 UTC
